version: "3"
services:
  pixel_battle_front:
    container_name: pixel_battle_front
    build:
      context: .
#      args:
#        backHost: "http://localhost"
#        backPath: "/pixel-battle-back"
#        frontHost: "http://localhost"
#        idpUrl: "http://localhost/oauth2"
    networks:
      - dc-net
networks:
  dc-net:
    external: true