version: "3"
services:
  pixel_battle_front:
    container_name: pixel_battle_front
    build: .
    networks:
      - dc-net
    environment:
      aga: 123
      age: 321
networks:
  dc-net:
    external: true